appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: G3p/NhjI2aMuRgWDiUd05mJm8Fs9C8297odIUDo8obR+MIa24Ck2MdRQHFWqAnKWKL1igHLBAWWbUhJ5hSmaGRLNT3KluDBhk00TTgNpyG+DltNRlXYvRUKzvT8IrR7VXZwEhhItvnXlYtg3UzJ1zhF6sEUggsq0AEgzqiYdz+KxHkeOol4XJwKOusIMC5n3kETbW//f8w3HnE2PkY3CM3WLo6M+st4XAEmjiFKDooDKtmJD9E6qhkkr3tBmjZXDUKCjqD8sNDxXehv+FwwdpJQMraBp8yFcj2f+MjocnpBVxTPgJlkDvI4QM031HPOgVLJN5jf6Mp1NExEsn0YMd+GOexo/jEa9sE9x8xqroLpD+Cvo/xADjzwcsDq1o5uE8qaObSl+jepgjWiRDLgICj+Vu1v8nH0tPy5+u/1xBYsM10b1Zkr2FDtLYApUMZK7MwFEMhZYUQf4VX2oeXkAvXl2Us2F9pcqmTAVF4sFKygmNgmLvq1Q3aav6Z25R9fhS5ajTHhbDaeYX5ocy3UF2pyIPuHAwuoXpwBWAhklWfOgrzfoUsjJZWZDdZg/yvadWIF4eAq1ke0Gp4vt4CTT15IIVstPevEYiJGDCVvO9a7TB/AtSA8WAExhZ1inCLGzQEyCHLNfM16aEKHCS1cCjKa4orKfGCFXUk24bec4pu0=
conda_forge_output_validation: true
